#!/usr/bin/env python3
"""
Retitle the résumé PDF in place: "UI/UX & Graphic Designer" -> the site's title.

Why this exists at all: the site says "Product Designer (Design + Front-End)"
everywhere, but the PDF it serves for download still led with the old title, and
the PDF is the artefact that reaches recruiters and ATS keyword filters. The
source document (Word/Docs) isn't in the repo, so the string is patched directly.

This is safe here, and only here, because of three properties of THIS file:
  1. It uses a classic cross-reference TABLE, not an xref stream, and has no
     object streams — so the xref can be regenerated by scanning object offsets.
  2. The title line is drawn by font F2 (Carlito-Regular), whose subset already
     contains every glyph the new title needs — no font has to be re-embedded.
  3. The line is page-centered, so the only geometry to recompute is the start x,
     from the font's own /Widths array.

Run:  python3 scripts/patch-resume-title.py            (verifies, writes)
      python3 scripts/patch-resume-title.py --dry-run  (verifies, writes nothing)

Always re-run scripts/verify-resume-pdf.py afterwards.
"""
import re
import sys
import zlib
from pathlib import Path

PDF = Path("public/pdf/Praduan_Saha_Resume.pdf")
# Both uppercase: the line is set in caps in the document, not styled to caps.
OLD_TITLE = "UI/UX & GRAPHIC DESIGNER"
NEW_TITLE = "PRODUCT DESIGNER (DESIGN + FRONT-END)"
PAGE_WIDTH = 612.0
FONT_SIZE = 10.0
# Letter-spacing the original line uses, as a TJ adjustment (thousandths of em).
KERN = -150


def parse_objects(data: bytes) -> dict[int, bytes]:
    return {
        int(m.group(1)): m.group(2)
        for m in re.finditer(rb"(\d+)\s+0\s+obj(.*?)endobj", data, re.S)
    }


def stream_bytes(body: bytes) -> tuple[bytes, bytes, bytes]:
    """Split an object body into (before, raw stream, after)."""
    m = re.search(rb"(stream\r?\n)(.*?)(\s*endstream)", body, re.S)
    if not m:
        raise SystemExit("content object has no stream")
    return body[: m.start(2)], m.group(2), body[m.end(2) :]


def parse_cmap(text: str) -> dict[int, str]:
    mp: dict[int, str] = {}
    for blk in re.findall(r"beginbfchar(.*?)endbfchar", text, re.S):
        for a, b in re.findall(r"<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>", blk):
            mp[int(a, 16)] = "".join(chr(int(b[i : i + 4], 16)) for i in range(0, len(b), 4))
    for blk in re.findall(r"beginbfrange(.*?)endbfrange", text, re.S):
        for a, b, c in re.findall(
            r"<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>", blk
        ):
            lo, hi, st = int(a, 16), int(b, 16), int(c, 16)
            for i in range(lo, hi + 1):
                mp[i] = chr(st + i - lo)
    return mp


def main() -> int:
    dry = "--dry-run" in sys.argv
    data = PDF.read_bytes()
    objs = parse_objects(data)

    # ---- Resolve font F2 (the title's font): its code->unicode map + widths ----
    fdict = objs[133].decode("latin-1")
    f2_num = int(dict(re.findall(r"/(F\d+)\s+(\d+)\s+0\s+R", fdict))["F2"])
    f2 = objs[f2_num].decode("latin-1")
    tu_num = int(re.search(r"/ToUnicode\s+(\d+)\s+0\s+R", f2).group(1))
    _, tu_raw, _ = stream_bytes(objs[tu_num])
    cmap = parse_cmap(zlib.decompress(tu_raw).decode("latin-1"))
    inv = {v: k for k, v in cmap.items()}

    first_char = int(re.search(r"/FirstChar\s+(\d+)", f2).group(1))
    widths = [
        float(w) for w in re.search(r"/Widths\[([^\]]*)\]", f2, re.S).group(1).split()
    ]

    missing = sorted({c for c in NEW_TITLE if c not in inv})
    if missing:
        raise SystemExit(f"F2 subset is missing glyphs {missing} — cannot patch safely")

    def advance(text: str) -> float:
        """Rendered width in points, including the line's letter-spacing."""
        w = sum(widths[inv[c] - first_char] for c in text) / 1000.0 * FONT_SIZE
        return w + (len(text) - 1) * (-KERN / 1000.0 * FONT_SIZE)

    # ---- Locate the title run in the page-1 content stream ----
    page1 = int(re.search(r"/Contents\s+(\d+)\s+0\s+R", objs[1].decode("latin-1")).group(1))
    pre, raw, post = stream_bytes(objs[page1])
    content = zlib.decompress(raw).decode("latin-1")

    # The one F2 10pt run whose decoded text is the old title.
    pattern = re.compile(
        r"(?P<x>[\d.]+)\s+(?P<y>[\d.]+)\s+Td\s*/F2\s+10\s+Tf\s*\[(?P<arr>.*?)\]TJ", re.S
    )
    hit = None
    for m in pattern.finditer(content):
        decoded = "".join(
            cmap.get(int(h[i : i + 2], 16), "")
            for h in re.findall(r"<([0-9A-Fa-f]+)>", m.group("arr"))
            for i in range(0, len(h), 2)
        )
        if decoded == OLD_TITLE:
            hit = m
            break
    if hit is None:
        raise SystemExit(f"could not find the run reading {OLD_TITLE!r} — file already patched?")

    old_x, y = float(hit.group("x")), float(hit.group("y"))
    old_w, new_w = advance(OLD_TITLE), advance(NEW_TITLE)
    # The StructElem for this run declares /TextAlign/Center; confirm the original
    # really is page-centered before re-centering the replacement on that basis.
    centered = abs((old_x + old_w / 2) - PAGE_WIDTH / 2) < 2.0
    new_x = round((PAGE_WIDTH - new_w) / 2, 2) if centered else old_x

    print(f"old: x={old_x} width={old_w:.2f} centered={centered}")
    print(f"new: x={new_x} width={new_w:.2f}  {NEW_TITLE!r}")
    if new_w > PAGE_WIDTH - 72:
        raise SystemExit("new title would run into the page margins — aborting")

    new_arr = f"{KERN}".join(f"<{inv[c]:02X}>" for c in NEW_TITLE)
    new_run = f"{new_x} {y} Td /F2 10 Tf[{new_arr}]TJ"
    content = content[: hit.start()] + new_run + content[hit.end() :]

    # ---- Recompress, fix /Length, rebuild the xref table ----
    new_raw = zlib.compress(content.encode("latin-1"), 9)

    # /Length here is an INDIRECT reference ("/Length 3 0 R" — object 3 holds the
    # number), which is how this producer writes it. Rewriting the digits in the
    # reference would point it at a nonexistent object; the length lives in the
    # referenced object, so that is what has to change. Handle both forms.
    indirect = re.search(rb"/Length\s+(\d+)\s+0\s+R", pre)
    length_obj = int(indirect.group(1)) if indirect else None
    if indirect:
        new_pre = pre  # reference stays as-is
    else:
        new_pre = re.sub(rb"/Length\s+\d+\b", b"/Length " + str(len(new_raw)).encode(), pre)

    new_body = new_pre + new_raw + post
    old_obj = b"%d 0 obj" % page1 + objs[page1] + b"endobj"
    new_obj = b"%d 0 obj" % page1 + new_body + b"endobj"
    out = data.replace(old_obj, new_obj, 1)
    if out == data:
        raise SystemExit("content object substitution failed")

    if length_obj is not None:
        old_len_obj = b"%d 0 obj" % length_obj + objs[length_obj] + b"endobj"
        if old_len_obj not in out:
            raise SystemExit(f"length object {length_obj} not found")
        new_len_obj = b"%d 0 obj\n%d\nendobj" % (length_obj, len(new_raw))
        out = out.replace(old_len_obj, new_len_obj, 1)
        print(f"length: object {length_obj} {objs[length_obj].strip().decode()} -> {len(new_raw)}")

    # Byte offsets after the edited object have all shifted; regenerate the table
    # from scratch by scanning, rather than patching offsets by a delta.
    #
    # Find the xref TABLE, not the word "xref" — rfind(b"xref") matches the four
    # bytes inside the trailing "startxref" keyword, which silently writes the new
    # table at the wrong offset and leaves the old one stranded in the file.
    xm = re.search(rb"\nxref\r?\n0\s+\d+\r?\n", out)
    if xm is None:
        raise SystemExit("no classic xref table found — this patcher does not handle xref streams")
    body_end = xm.start() + 1
    offsets = {
        int(m.group(1)): m.start()
        for m in re.finditer(rb"(?m)^(\d+)\s+0\s+obj", out[:body_end])
    }
    size = max(offsets) + 1
    if sorted(offsets) != list(range(1, size)):
        raise SystemExit(f"object numbering is not contiguous: {sorted(offsets)[:5]}…")

    xref = [b"xref\n", b"0 %d\n" % size, b"0000000000 65535 f \n"]
    xref += [b"%010d 00000 n \n" % offsets[i] for i in range(1, size)]
    trailer = re.search(rb"trailer.*?>>", data, re.S).group(0)
    startxref = body_end
    out = out[:body_end] + b"".join(xref) + trailer + b"\nstartxref\n%d\n%%%%EOF\n" % startxref

    if dry:
        print("dry run — nothing written")
        return 0
    PDF.write_bytes(out)
    print(f"wrote {PDF} ({len(out)} bytes, was {len(data)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
