#!/usr/bin/env python3
"""
Fold the InsightsTap internship into the full-time role, in the résumé PDF.

Why this exists: LinkedIn (and now /resume and the About timeline) show ONE
unbroken InsightsTap role — Graphic Designer, Full-time, On-site, Sep 2025 –
Present. The PDF still splits it into an internship (Sep 2025 – Feb 2026) and
the full-time role that followed, and the PDF is the artefact that reaches
recruiters and ATS parsers. The source document (Word/Docs) isn't in the repo,
so the change is made directly on the file.

Three edits, all on page 1:
  1. Delete the "Graphic Designer · Internship · Remote" heading and its two
     STAR bullets outright (15 marked-content blocks).
  2. Retitle two date runs: the role dateline "Feb 2026 – Present" ->
     "Sep 2025 – Present", and the company dateline's stale "· 10 mos" -> the
     "· 1 yr" LinkedIn now shows.
  3. Reflow: shift everything below the cut UP so no hole is left, using the
     document's own company-heading gap so the spacing stays native.

This is safe on THIS file because of four properties of it:
  a. Classic cross-reference TABLE, no object streams, so the xref can be
     regenerated by scanning object offsets.
  b. Every visual line is its own marked-content block with an ABSOLUTE `Td`
     position, so deleting lines and shifting the rest is arithmetic, not
     text re-flow. Nothing wraps, so no line has to be re-broken.
  c. Page 1's three section rules all sit ABOVE the cut (y 682.6 / 608.7 /
     531.7 vs a cut at y 380.5), so no drawn geometry moves.
  d. The replacement date strings need only glyphs the F2 subset already
     carries (they are already on the page), so no font is re-embedded.

The document is TAGGED, so the structure tree is repaired too: MCIDs are
renumbered contiguously, every StructElem's /K is remapped, elements left with
no content are pruned from their parent, and the /ParentTree is rebuilt. Text
extraction ignores all of that; screen readers and some ATS parsers do not.

Content is NOT moved between pages. Page 1 simply ends ~74pt higher, at a clean
bullet boundary. Pulling page 2's text up would mean moving struct elements
across /Pg boundaries, which is a re-export job, not a byte patch.

Run:  python3 scripts/patch-resume-insightstap.py            (verifies, writes)
      python3 scripts/patch-resume-insightstap.py --dry-run  (verifies, writes nothing)

Always re-run scripts/verify-resume-pdf.py afterwards.
"""
import re
import sys
import zlib
from pathlib import Path

PDF = Path("public/pdf/Praduan_Saha_Resume.pdf")

# The heading that opens the block to delete, and the heading that closes it.
CUT_FROM = "Graphic Designer · Internship · Remote"
CUT_TO = "Learning Designer"
# The heading whose spacing defines the gap the reflow must reproduce: it is the
# next company heading after a role's last bullet, exactly what CUT_TO becomes.
GAP_MODEL = "Content Developer"

EDITS = {
    "Feb 2026 – Present": "Sep 2025 – Present",
    "Sep 2025 – Present · 10 mos": "Sep 2025 – Present · 1 yr",
}

# Tag names vary (/Standard, /Lbl, /List#20Paragraph, /LBody…): capture the tag
# and re-emit it verbatim rather than assuming every block is /Standard.
BLOCK = re.compile(rb"/([A-Za-z0-9#]+)<</MCID (\d+)>>BDC\n(.*?)\nEMC\n", re.S)
TD = re.compile(rb"([\d.]+) ([\d.]+) Td /(F\d+) ([\d.]+) Tf")


def parse_objects(data: bytes) -> dict[int, bytes]:
    return {
        int(m.group(1)): m.group(2)
        for m in re.finditer(rb"(\d+)\s+0\s+obj(.*?)endobj", data, re.S)
    }


def stream_bytes(body: bytes) -> tuple[bytes, bytes, bytes]:
    m = re.search(rb"(stream\r?\n)(.*?)(\s*endstream)", body, re.S)
    if not m:
        raise SystemExit("object has no stream")
    return body[: m.start(2)], m.group(2), body[m.end(2) :]


def parse_cmap(text: str) -> dict[int, str]:
    mp: dict[int, str] = {}
    for blk in re.findall(r"beginbfchar(.*?)endbfchar", text, re.S):
        for a, b in re.findall(r"<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>", blk):
            mp[int(a, 16)] = "".join(chr(int(b[i : i + 4], 16)) for i in range(0, len(b), 4))
    for blk in re.findall(r"beginbfrange(.*?)endbfrange", text, re.S):
        for a, b, c in re.findall(
            r"<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>", blk
        ):
            lo, hi, st = int(a, 16), int(b, 16), int(c, 16)
            for i in range(lo, hi + 1):
                mp[i] = chr(st + i - lo)
    return mp


def main() -> int:
    dry = "--dry-run" in sys.argv
    data = PDF.read_bytes()
    objs = parse_objects(data)

    # ---- Font maps, so blocks can be matched on what they READ, not offsets --
    fdict = dict(re.findall(rb"/(F\d+)\s+(\d+)\s+0\s+R", objs[133]))
    cmaps: dict[bytes, dict[int, str]] = {}
    for name, num in fdict.items():
        f = objs[int(num)].decode("latin-1")
        tu = int(re.search(r"/ToUnicode\s+(\d+)\s+0\s+R", f).group(1))
        _, raw, _ = stream_bytes(objs[tu])
        cmaps[name] = parse_cmap(zlib.decompress(raw).decode("latin-1"))

    def decode(body: bytes, font: bytes) -> str:
        cm = cmaps[font]
        after = body[TD.search(body).end() :]
        return "".join(
            cm.get(int(h[i : i + 2], 16), "")
            for h in re.findall(rb"<([0-9A-Fa-f]+)>", after)
            for i in range(0, len(h.decode()), 2)
        )

    # ---- Read page 1 as an ordered list of marked-content blocks -------------
    page1_num = int(re.search(r"/Contents\s+(\d+)\s+0\s+R", objs[1].decode("latin-1")).group(1))
    pre, raw, post = stream_bytes(objs[page1_num])
    content = zlib.decompress(raw)

    blocks = []
    for m in BLOCK.finditer(content):
        td = TD.search(m.group(3))
        blocks.append(
            {
                "span": (m.start(), m.end()),
                "tag": m.group(1),
                "mcid": int(m.group(2)),
                "body": m.group(3),
                "y": float(td.group(2)) if td else None,
                "font": td.group(3) if td else None,
                "text": decode(m.group(3), td.group(3)) if td else "",
            }
        )
    ids = [b["mcid"] for b in blocks]
    if ids != list(range(len(ids))):
        raise SystemExit("page-1 MCIDs are not contiguous; refusing to renumber")

    def only(label: str) -> int:
        hits = [i for i, b in enumerate(blocks) if b["text"] == label]
        if len(hits) != 1:
            raise SystemExit(f"expected exactly one block reading {label!r}, found {len(hits)}")
        return hits[0]

    i_from, i_to = only(CUT_FROM), only(CUT_TO)
    if not 0 < i_from < i_to:
        raise SystemExit("cut boundaries are out of order")

    # ---- Reflow distance, measured from the document's own spacing ----------
    i_gap = only(GAP_MODEL)
    gap = round(blocks[i_gap - 1]["y"] - blocks[i_gap]["y"], 2)
    target_y = round(blocks[i_from - 1]["y"] - gap, 2)
    shift = round(target_y - blocks[i_to]["y"], 2)
    if not 0 < shift < 200:
        raise SystemExit(f"implausible reflow shift {shift}")

    cut = blocks[i_from:i_to]
    print(f"cut     : {len(cut)} blocks, MCID {cut[0]['mcid']}–{cut[-1]['mcid']}, "
          f"y {cut[0]['y']} → {cut[-1]['y']}")
    print(f"gap     : {gap}pt (from {GAP_MODEL!r})")
    print(f"reflow  : {CUT_TO!r} y {blocks[i_to]['y']} → {target_y} (shift +{shift})")

    # Nothing drawn may sit in the region that moves: the rules are artifacts
    # outside the marked-content blocks and are NOT shifted, so verify they are
    # all above the cut rather than assuming it.
    rules = [float(y) for y in re.findall(rb"[\d.]+ ([\d.]+) m\n", content)]
    below = [y for y in rules if y < blocks[i_from - 1]["y"]]
    if below:
        raise SystemExit(f"drawn rules sit below the cut and would not reflow: {below}")
    print(f"rules   : {len(set(rules))} distinct, all above the cut ✓")

    # ---- Rebuild the content stream -----------------------------------------
    dead = {b["mcid"] for b in cut}
    remap: dict[int, int] = {}
    shifted: dict[int, int] = {}
    out, cursor, next_id = bytearray(), 0, 0
    for b in blocks:
        start, end = b["span"]
        out += content[cursor:start]
        cursor = end
        if b["mcid"] in dead:
            continue
        body = b["body"]
        if b["text"] in EDITS:
            new = EDITS[b["text"]]
            inv = {v: k for k, v in cmaps[b["font"]].items()}
            missing = sorted({c for c in new if c not in inv})
            if missing:
                raise SystemExit(f"font subset lacks glyphs {missing} for {new!r}")
            hexs = "".join(f"{inv[c]:02X}" for c in new).encode()
            if len(TD.findall(body)) != 1:
                raise SystemExit(f"block {b['mcid']} has several runs; cannot retitle safely")
            td = TD.search(body)
            arr = re.compile(rb"\[.*?\]TJ|<[0-9A-Fa-f]*>Tj", re.S).search(body, td.end())
            body = body[: arr.start()] + b"<" + hexs + b">Tj" + body[arr.end() :]
            print(f"retitle : {b['text']!r} -> {new!r}")
        if b["mcid"] > cut[-1]["mcid"]:
            # Every run in the block, not just the first: one marked-content
            # block can hold several BT/ET pairs (a line whose font changes
            # mid-way is split in two), and a run left at its old baseline
            # floats away from the line it belongs to.
            def bump(m: "re.Match[bytes]") -> bytes:
                y = round(float(m.group(2)) + shift, 2)
                return b"%s %s Td /%s %s Tf" % (
                    m.group(1), f"{y:g}".encode(), m.group(3), m.group(4)
                )

            body, n = TD.subn(bump, body)
            shifted[b["mcid"]] = n
        remap[b["mcid"]] = next_id
        out += b"/%s<</MCID %d>>BDC\n" % (b["tag"], next_id) + body + b"\nEMC\n"
        next_id += 1
    out += content[cursor:]
    content_new = bytes(out)
    print(f"mcids   : {len(blocks)} -> {next_id}")

    lows = [round(b["y"] + shift, 2) for b in blocks if b["mcid"] > cut[-1]["mcid"]]
    print(f"shift   : {len(shifted)} blocks, {sum(shifted.values())} runs "
          f"({sum(1 for n in shifted.values() if n > 1)} with more than one)")
    print(f"page 1  : lowest baseline {min(lows)} (was {min(b['y'] for b in blocks)})")

    # ---- Repair the structure tree ------------------------------------------
    data = repair_struct(data, objs, remap, dead)

    # ---- Splice the new stream in, fix /Length, rebuild the xref ------------
    new_raw = zlib.compress(content_new, 9)
    length_obj = int(re.search(rb"/Length\s+(\d+)\s+0\s+R", pre).group(1))
    objs2 = parse_objects(data)
    old_obj = b"%d 0 obj" % page1_num + objs2[page1_num] + b"endobj"
    new_obj = b"%d 0 obj" % page1_num + pre + new_raw + post + b"endobj"
    data = data.replace(old_obj, new_obj, 1)
    old_len = b"%d 0 obj" % length_obj + objs2[length_obj] + b"endobj"
    data = data.replace(old_len, b"%d 0 obj\n%d\nendobj" % (length_obj, len(new_raw)), 1)
    print(f"length  : object {length_obj} -> {len(new_raw)}")

    data = rebuild_xref(data)

    if dry:
        print("dry run: nothing written")
        return 0
    PDF.write_bytes(data)
    print(f"wrote {PDF} ({len(data)} bytes)")
    return 0


def repair_struct(data: bytes, objs: dict[int, bytes], remap: dict[int, int],
                  dead: set[int]) -> bytes:
    """Remap MCIDs in every page-1 StructElem, prune what is left empty.

    Emptied elements are unlinked from their parent's /K but their object bodies
    stay in the file as orphans. That keeps object numbering contiguous, which
    the xref rebuild depends on; unreferenced objects are legal and ignored.
    """
    page1_ref = b"/Pg 1 0 R"
    kids: dict[int, list] = {}
    for num, body in objs.items():
        if b"/Type/StructElem" not in body:
            continue
        km = re.search(rb"/K\[(.*?)\]", body, re.S)
        if not km:
            continue
        toks, pos = [], 0
        for t in re.finditer(rb"(\d+)\s+0\s+R|(\d+)", km.group(1)):
            toks.append(("ref", int(t.group(1))) if t.group(1) else ("mcid", int(t.group(2))))
        kids[num] = toks
        if page1_ref not in body:
            continue
        new = [t for t in toks if t[0] != "mcid" or t[1] not in dead]
        new = [(k, remap[v] if k == "mcid" else v) for k, v in new]
        kids[num] = new

    parent = {v: num for num, toks in kids.items() for k, v in toks if k == "ref"}
    # Cascade: an element with no kids left is unlinked from its parent, which may
    # in turn empty the parent.
    changed = True
    while changed:
        changed = False
        for num, toks in list(kids.items()):
            if toks or num not in parent:
                continue
            p = parent[num]
            if any(k == "ref" and v == num for k, v in kids[p]):
                kids[p] = [t for t in kids[p] if t != ("ref", num)]
                changed = True
    pruned = [n for n, t in kids.items() if not t]
    print(f"struct  : {sum(1 for b in objs.values() if b'/Type/StructElem' in b)} elems, "
          f"{len(pruned)} emptied and unlinked {pruned or ''}")

    for num, toks in kids.items():
        body = objs[num]
        km = re.search(rb"/K\[(.*?)\]", body, re.S)
        rendered = b" ".join(
            (b"%d 0 R" % v) if k == "ref" else (b"%d" % v) for k, v in toks
        )
        new_body = body[: km.start(1)] + rendered + (b" " if toks else b"") + body[km.end(1) :]
        if new_body != body:
            data = data.replace(b"%d 0 obj" % num + body + b"endobj",
                                b"%d 0 obj" % num + new_body + b"endobj", 1)
    return rebuild_parent_tree(data, remap, dead)


def rebuild_parent_tree(data: bytes, remap: dict[int, int], dead: set[int]) -> bytes:
    """Rewrite /ParentTree Nums[0]: one entry per surviving page-1 MCID, in order."""
    pt = int(re.search(rb"/ParentTree (\d+) 0 R", data).group(1))
    body = re.search(rb"(?:^|\n)%d 0 obj\n(.*?)\nendobj" % pt, data, re.S).group(1)
    nums = re.search(rb"0 \[(.*?)\]", body, re.S)
    entries = re.findall(rb"(\d+) 0 R", nums.group(1))
    # Nums[0] is indexed BY MCID, so it must have had one entry per original
    # page-1 MCID. If it does not, the index arithmetic below is meaningless.
    if len(entries) != len(remap) + len(dead):
        raise SystemExit(f"ParentTree page-1 has {len(entries)} entries, "
                         f"expected {len(remap) + len(dead)}")
    kept = [entries[old] for old in sorted(remap, key=lambda o: remap[o])]
    lines, row = [], []
    for e in kept:
        row.append(b"%s 0 R" % e)
        if len(row) == 10:
            lines.append(b" ".join(row))
            row = []
    if row:
        lines.append(b" ".join(row))
    rendered = b"\n".join(lines) + b" "
    new_body = body[: nums.start(1)] + rendered + body[nums.end(1) :]
    print(f"partree : page-1 entries {len(entries)} -> {len(kept)}")
    return data.replace(b"%d 0 obj\n" % pt + body, b"%d 0 obj\n" % pt + new_body, 1)


def rebuild_xref(data: bytes) -> bytes:
    xm = re.search(rb"\nxref\r?\n0\s+\d+\r?\n", data)
    if xm is None:
        raise SystemExit("no classic xref table found")
    body_end = xm.start() + 1
    offsets = {
        int(m.group(1)): m.start()
        for m in re.finditer(rb"(?m)^(\d+)\s+0\s+obj", data[:body_end])
    }
    size = max(offsets) + 1
    if sorted(offsets) != list(range(1, size)):
        raise SystemExit("object numbering is not contiguous")
    xref = [b"xref\n", b"0 %d\n" % size, b"0000000000 65535 f \n"]
    xref += [b"%010d 00000 n \n" % offsets[i] for i in range(1, size)]
    trailer = re.search(rb"trailer.*?>>", data, re.S).group(0)
    return data[:body_end] + b"".join(xref) + trailer + b"\nstartxref\n%d\n%%%%EOF\n" % body_end


if __name__ == "__main__":
    raise SystemExit(main())
